title: miro makes
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: portfolio of miro voellmy
color_scheme: light
accent_color: yellow
header:
  title: miro makes
  has_nav: true
  nav_links:
    - label: main
      url: /
      style: link
    - label: me
      url: /about/
      style: link
    - label: my work
      url: /portfolio/
      style: link
    - label: mail me
      url: /contact/
      style: link
  logo_img: images/miro_makes.png
footer:
  content: >-
    &copy; 2021, Miro Voellmy. All rights reserved. This Jamstack site was created on <a
    href="https://www.stackbit.com" target="_blank" rel="noopener">Stackbit</a>.
    Get yours <a href="https://app.stackbit.com/create?theme=exto"
    target="_blank" rel="noopener">here</a>.
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://www.github.com/mvoellmy/'
      style: icon
      icon_class: fa-github
      new_window: true
      type: action
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/mirovoellmy/'
      style: icon
      icon_class: fa-linkedin
      new_window: true
      type: action
    - label: Twitter
      url: 'https://twitter.com/miro_makes'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/miro.makes/'
      style: icon
      icon_class: fa-instagram
      new_window: true


sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
